/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetIncidentAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { incidentId: string; data: unknown }> | ApiResponse<404, { error: string }>, never>
    'IncidentAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string }> | ApiResponse<400, { error: string }>, { topic: 'incident-created'; data: { incidentId: string; createdAt: string; title: string; description?: string; source: string } }>
    'IncidentEscalationChecker': CronHandler<never>
    'IncidentCreated': EventHandler<{ incidentId: string; createdAt: string; title: string; description?: string; source: 'user' | 'monitoring' | 'webhook' }, never>
    'IncidentClassifier': EventHandler<{ incidentId: string; createdAt: string; title: string; description?: string; source: 'user' | 'monitoring' | 'webhook' }, { topic: 'incident-classified'; data: { incidentId: string; priority: 'HIGH' | 'MEDIUM' | 'LOW' } }>
    'IncidentClassified': EventHandler<{ incidentId: string; priority: 'HIGH' | 'MEDIUM' | 'LOW' }, never>
  }
    
}